[workspace]
resolver = "2"
members = [
    "crates/discovery",
    "crates/net",
]

default-members = [
    "crates/discovery",
    "crates/net",
]

[profile.release]
panic = "abort"
debug = true
lto = "thin"