[package]
name = "discovery"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"]}
anyhow = "1"
rand = "0.8"
futures-lite = "1"
bytes = "1"
mainline = "5.3.1"
ed25519-dalek = { version = "2.0.0", features = ["serde", "rand_core"] }
once_cell = "1"